### ISSUE TITLE
Add licence to repo

### ISSUE THREAD

**Issue by absolly** [max-verem/FreeDLiveLink#2]
Hey Maksym, 

I would like to use this plugin as a base to work of for a project, however, I would need have a licence to properly make use of this code. Could you add a licence to the repo so I know what I can and can't use this plugin for?

**Comment by max-verem** [comment]
what kind of license is preferred?

**Comment by absolly** [comment]
The MIT license as it is simple and permissive https://choosealicense.com/licenses/mit/

**Comment by max-verem** [comment]
https://github.com/max-verem/FreeDLiveLink/commit/6d1cc8a5b5880daa443148883c0e25f44cf92c28

**Comment by absolly** [comment]
Awesome, thanks for the quick response!
